########################################################################################################################
# Memo:
########################################################################################################################

# This file is used to configure content of packages.

# Mappings ($ string substitutions). Name and examples:
# |==========================================================
# | $platform      | 'windows-x86_64'     | 'linux-x86_64'  |
# |----------------------------------------------------------
# | $lib_ext       | '.dll'               | '.so'           |
# | $lib_prefix    | ''                   | 'lib.'          |
# | $bindings_ext  | '.pyd'               | '.so'           |
# | $exe_ext       | '.exe'               | ''              |
# | $shell_ext     | '.bat'               | '.sh'           |
# |==========================================================
#
# |==========================================================
# | $config        | 'debug'              | 'release'       |
# |==========================================================

# Filters. For example, if packaging carb_sdk, debug, on linux-x86_64 all those toml keys will be used for this package:
# [carb_sdk.linux-x86_64]
# [carb_sdk.debug]
# [carb_sdk.linux.debug]
# So you can use those in any order as a keys: ["carb_sdk", "linux-x86_64", "debug", "linux", "x86_64"]


########################################################################################################################
# Common section:
########################################################################################################################

files = []

########################################################################################################################
# isaac-sim package
########################################################################################################################

[isaac-sim-docker]
files = [
    # Goes source path destination path.  If no destination path it will be inferred as top level.
    [".vscode"],
]
files_exclude = [
    ["**/*.pyc"],
    ["**/*.pdb"],
    ["**/*.exp"],
    ["**/*.a"], # static libs
    ["apps/exts.deps.generated.kit"],
    ["apps/isaacsim.exp.extscache.*"],
    ["kit/data/**"], # This can contain portable files we don't want to package
    ["kit/logs/**"],
    ["logs/**"],
    ["/extsbuild"],
    ["/dev"],
    ["tests/tests-internal*"],
    ["tests/tests-docker*"],
    ["dockertests/**"],
    ["tests-external/**"],
    ["exts/omni.isaac.core_archive/pip_prebundle/bin/**"],
    ["tests/tests-startup.extscache*"],
    ["tests/tests-omni.importer.onshape*"],
    ["kit/exts/omni.kit.extpath.git/**"],
    ["**/.git/**"],
    ["pull_kit_sdk*"],
    ["run_all_*"],
    ["compile_commands.json"],
    ["exts/*/pip_*/**/*.exe"],
    ["extscache/*/pip_*/**/*.exe"],
]

files_strip = [
    ["**/*.so"],
]

files_strip_exclude = [
    ["*extscache/omni.kit.pip_archive*/pip_prebundle/**"],
    ["*exts/omni.isaac.ml_archive/pip_prebundle/**"],
    ["*exts/omni.isaac.core_archive/pip_prebundle/**"],
    ["*exts/omni.pip.cloud/pip_prebundle/**"],
    ["*exts/omni.pip.compute/pip_prebundle/**"],
    ["*libscipy_openblas*.so"],
]

[isaac-sim-docker.linux-x86_64]
files = [
    ["_build/linux-x86_64/release/**", "."],
    ["_build/docs/isaac_sim/latest/**", "docs/py/"],
]

[isaac-sim-docker.linux-aarch64]
files = [
    ["_build/linux-aarch64/release/**", "."]
]
